package me.bounser.nascraft.exchange.clob;

import me.bounser.nascraft.exchange.integrity.CircuitBreaker;
import me.bounser.nascraft.exchange.integrity.MarketStateManager;

import java.math.BigDecimal;
import java.util.*;
import java.util.function.Consumer;
import java.util.concurrent.ConcurrentHashMap;

/**
 * Central Limit Order Book matching engine.
 *
 * Price-time priority:
 *  - Best price matched first.
 *  - Within the same price level, FIFO (insertion order).
 *
 * Market orders: match at any available price.
 * Limit orders:  BUY matches asks where ask ≤ bid price; SELL matches bids where bid ≥ ask price.
 *
 * Thread-safety: submitOrder is synchronized per-ticker via the OrderBook monitor.
 */
public class MatchingEngine {

    private static MatchingEngine instance;

    private final Map<String, OrderBook> orderBooks = new ConcurrentHashMap<>();
    private Consumer<Fill> fillListener;

    private MatchingEngine() {}

    public static MatchingEngine getInstance() {
        if (instance == null) instance = new MatchingEngine();
        return instance;
    }

    public void setFillListener(Consumer<Fill> listener) {
        this.fillListener = listener;
    }

    // ── Public API ────────────────────────────────────────────────────────────

    public OrderBook getOrCreateBook(String ticker) {
        return orderBooks.computeIfAbsent(ticker.toUpperCase(), OrderBook::new);
    }

    public Optional<OrderBook> getBook(String ticker) {
        return Optional.ofNullable(orderBooks.get(ticker.toUpperCase()));
    }

    /**
     * Submit an order and attempt to match it immediately.
     * @return list of fills generated by this order
     */
    public synchronized List<Fill> submitOrder(ExchangeOrder order) {
        if (!MarketStateManager.getInstance().isOpen()) {
            return Collections.emptyList();
        }

        OrderBook book = getOrCreateBook(order.getTickerSymbol());
        List<Fill> fills = matchOrder(book, order);

        // If LIMIT order has remaining quantity and wasn't cancelled, add to book
        if (order.getType() == OrderType.LIMIT && order.isActive()) {
            book.addOrder(order);
        }

        return fills;
    }

    public boolean cancelOrder(String ticker, UUID orderId) {
        OrderBook book = orderBooks.get(ticker.toUpperCase());
        if (book == null) return false;
        return book.cancelOrder(orderId);
    }

    // ── Private Matching Logic ────────────────────────────────────────────────

    private List<Fill> matchOrder(OrderBook book, ExchangeOrder incoming) {
        List<Fill> fills = new ArrayList<>();

        if (incoming.getSide() == OrderSide.BUY) {
            matchAgainstAsks(book, incoming, fills);
        } else {
            matchAgainstBids(book, incoming, fills);
        }

        return fills;
    }

    /** Incoming BUY: match against the ask side (lowest ask first). */
    private void matchAgainstAsks(OrderBook book, ExchangeOrder incoming, List<Fill> fills) {
        TreeMap<BigDecimal, LinkedList<ExchangeOrder>> asks = book.getAsks();

        Iterator<Map.Entry<BigDecimal, LinkedList<ExchangeOrder>>> it = asks.entrySet().iterator();
        while (it.hasNext() && incoming.getRemainingQuantity().compareTo(BigDecimal.ZERO) > 0) {
            Map.Entry<BigDecimal, LinkedList<ExchangeOrder>> entry = it.next();
            BigDecimal askPrice = entry.getKey();

            // Price check: LIMIT orders only match if ask ≤ bid price
            if (incoming.getType() == OrderType.LIMIT &&
                    askPrice.compareTo(incoming.getPrice()) > 0) {
                break; // asks are sorted ascending; no cheaper asks exist
            }

            LinkedList<ExchangeOrder> queue = entry.getValue();
            while (!queue.isEmpty() && incoming.getRemainingQuantity().compareTo(BigDecimal.ZERO) > 0) {
                ExchangeOrder maker = queue.peekFirst();
                if (!maker.isActive() || maker.isExpired()) {
                    queue.pollFirst();
                    continue;
                }

                // Wash trade check
                if (CircuitBreaker.getInstance().checkWashTrade(
                        incoming.getTickerSymbol(), incoming.getOwnerUuid(), maker.getOwnerUuid())) {
                    return; // market halted
                }

                BigDecimal fillQty = incoming.getRemainingQuantity()
                        .min(maker.getRemainingQuantity());
                BigDecimal fillPrice = askPrice; // maker's price

                maker.fill(fillQty);
                incoming.fill(fillQty);

                if (!maker.isActive()) queue.pollFirst();

                Fill fill = new Fill(maker, incoming, fillQty, fillPrice);
                fills.add(fill);
                if (fillListener != null) fillListener.accept(fill);

                // Circuit breaker: price spike check
                CircuitBreaker.getInstance().checkPriceSpike(incoming.getTickerSymbol(), fillPrice);
            }

            if (queue.isEmpty()) it.remove();
        }
    }

    /** Incoming SELL: match against the bid side (highest bid first). */
    private void matchAgainstBids(OrderBook book, ExchangeOrder incoming, List<Fill> fills) {
        TreeMap<BigDecimal, LinkedList<ExchangeOrder>> bids = book.getBids();

        Iterator<Map.Entry<BigDecimal, LinkedList<ExchangeOrder>>> it = bids.entrySet().iterator();
        while (it.hasNext() && incoming.getRemainingQuantity().compareTo(BigDecimal.ZERO) > 0) {
            Map.Entry<BigDecimal, LinkedList<ExchangeOrder>> entry = it.next();
            BigDecimal bidPrice = entry.getKey();

            // Price check: LIMIT orders only match if bid ≥ ask price
            if (incoming.getType() == OrderType.LIMIT &&
                    bidPrice.compareTo(incoming.getPrice()) < 0) {
                break; // bids are sorted descending; no better bids remain
            }

            LinkedList<ExchangeOrder> queue = entry.getValue();
            while (!queue.isEmpty() && incoming.getRemainingQuantity().compareTo(BigDecimal.ZERO) > 0) {
                ExchangeOrder maker = queue.peekFirst();
                if (!maker.isActive() || maker.isExpired()) {
                    queue.pollFirst();
                    continue;
                }

                if (CircuitBreaker.getInstance().checkWashTrade(
                        incoming.getTickerSymbol(), maker.getOwnerUuid(), incoming.getOwnerUuid())) {
                    return;
                }

                BigDecimal fillQty = incoming.getRemainingQuantity()
                        .min(maker.getRemainingQuantity());
                BigDecimal fillPrice = bidPrice;

                maker.fill(fillQty);
                incoming.fill(fillQty);

                if (!maker.isActive()) queue.pollFirst();

                Fill fill = new Fill(maker, incoming, fillQty, fillPrice);
                fills.add(fill);
                if (fillListener != null) fillListener.accept(fill);

                CircuitBreaker.getInstance().checkPriceSpike(incoming.getTickerSymbol(), fillPrice);
            }

            if (queue.isEmpty()) it.remove();
        }
    }
}
